{
    'name': 'car_service',
    'version': '',
    'summary': '',
    'description': '',
    'category': '',
    'author': '',
    'website': '',
    'license': '',
    'depends': [''],
    'data': ['views/car_service_view.xml',
             'views/menuitems.xml',
             ],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}